import type { Metadata } from "next"
import Navbar from "@/shared/components/Navbar/Navbar"
import styles from "./terms.module.css"

export const metadata: Metadata = { title: "Syarat dan Ketentuan | ITB Insight 2026" }

export default function TermsAndConditionsPage() {
  return <><Navbar isSolid /><main className={styles.page}><article className={styles.article}>
    <p className={styles.eyebrow}>ITB INSIGHT 2026 · HMFT-ITB</p><h1>Syarat dan Ketentuan ITB Insight 2026</h1><p className={styles.updated}>Terakhir diperbarui: Agustus 2026</p>
    <p>Syarat dan Ketentuan ini mengatur penggunaan website, pendaftaran, pembayaran, dan partisipasi dalam rangkaian kompetisi ITB Insight 2026.</p><p>Dengan melakukan pendaftaran dan menyetujui Syarat dan Ketentuan ini, peserta dianggap telah membaca, memahami, dan menyetujui ketentuan yang tercantum di bawah ini.</p>
    <h2>1. Penyelenggara</h2><p>ITB Insight 2026 merupakan kegiatan yang diselenggarakan di bawah <strong>Himpunan Mahasiswa Fisika Teknik Institut Teknologi Bandung (HMFT-ITB)</strong>.</p><p>Dalam dokumen ini, penyelenggara ITB Insight 2026 selanjutnya disebut sebagai <strong>“Panitia”</strong>.</p>
    <h2>2. Ruang Lingkup</h2><p>Syarat dan Ketentuan ini berlaku untuk proses pendaftaran dan partisipasi dalam kompetisi yang diselenggarakan sebagai bagian dari ITB Insight 2026.</p><p>Ketentuan teknis setiap kompetisi, termasuk tetapi tidak terbatas pada persyaratan peserta, format kompetisi, tahapan seleksi, mekanisme penilaian, ketentuan karya, jadwal, dan ketentuan teknis lainnya dapat diatur lebih lanjut dalam halaman kompetisi, guidebook, rulebook, atau pengumuman resmi masing-masing kompetisi.</p>
    <h2>3. Pendaftaran</h2><p>Pendaftaran dilakukan melalui website resmi ITB Insight 2026.</p><p>Peserta wajib memberikan data dan dokumen yang benar, lengkap, serta dapat dipertanggungjawabkan sesuai dengan persyaratan kompetisi yang diikuti.</p><p>Untuk kompetisi berbentuk tim, proses pendaftaran dilakukan oleh <strong>ketua tim</strong>.</p><p>Dengan melakukan pendaftaran, ketua tim menyatakan bahwa:</p><ol><li>seluruh informasi mengenai dirinya dan anggota tim yang diberikan kepada Panitia adalah benar;</li><li>seluruh anggota tim telah mengetahui keikutsertaannya dalam kompetisi;</li><li>ketua tim memiliki kewenangan untuk melakukan proses pendaftaran tim; dan</li><li>seluruh anggota tim memenuhi persyaratan kompetisi yang diikuti.</li></ol><p>Setelah pendaftaran dilakukan, anggota tim yang telah terdaftar <strong>tidak dapat ditambah, diganti, atau dikeluarkan</strong>, kecuali Panitia secara tertulis menentukan lain karena keadaan tertentu.</p><p>Satu peserta hanya diperbolehkan terdaftar pada <strong>satu kompetisi ITB Insight 2026</strong>.</p>
    <h2>4. Peserta di Bawah Umur</h2><p>Dalam hal peserta tergolong sebagai anak berdasarkan ketentuan peraturan perundang-undangan yang berlaku, keikutsertaan dan pemrosesan Data Pribadi peserta wajib memperoleh persetujuan dari orang tua atau wali.</p><p>Panitia dapat meminta konfirmasi atau bukti persetujuan orang tua/wali apabila diperlukan.</p>
    <h2>5. Status Registrasi dan Pembayaran</h2><p>Status <strong>registrasi</strong> dan status <strong>pembayaran</strong> merupakan dua status yang berbeda.</p><p>Tercatatnya registrasi peserta atau tim pada sistem tidak berarti pembayaran telah berhasil atau pendaftaran telah terkonfirmasi sepenuhnya.</p><p>Peserta bertanggung jawab untuk memastikan bahwa pembayaran telah berhasil sebelum batas waktu pembayaran berakhir.</p>
    <h2>6. Harga Pendaftaran</h2><p>Seluruh biaya pendaftaran ditampilkan dalam mata uang <strong>Rupiah (IDR)</strong>.</p><p>Biaya pendaftaran dapat berbeda berdasarkan kompetisi dan periode pendaftaran yang berlaku.</p><p>Nominal pembayaran yang berlaku adalah nominal yang ditampilkan ketika transaksi pembayaran dibuat.</p><p>Apabila transaksi tersebut kedaluwarsa dan peserta membuat transaksi baru, harga yang berlaku mengikuti harga pada saat transaksi baru dibuat.</p>
    <h2>7. Batas Waktu Pembayaran</h2><p>Setelah transaksi pembayaran dibuat, peserta diberikan waktu <strong>1 (satu) jam</strong> untuk menyelesaikan pembayaran.</p><p>Apabila pembayaran tidak berhasil diselesaikan dalam jangka waktu tersebut, transaksi dapat dinyatakan kedaluwarsa.</p><p>Peserta dapat diminta membuat transaksi pembayaran baru apabila tetap ingin melanjutkan proses pendaftaran.</p><p>Harga pada transaksi baru mengikuti periode harga yang berlaku pada saat transaksi baru dibuat.</p>
    <h2>8. Konfirmasi Pembayaran</h2><p>Pembayaran dianggap berhasil setelah sistem pembayaran memberikan konfirmasi keberhasilan transaksi kepada sistem ITB Insight.</p><p>Peserta bertanggung jawab untuk memeriksa status transaksi dan memastikan pembayaran telah berhasil.</p><p>Apabila terdapat perbedaan antara bukti pembayaran peserta dengan status yang tercatat pada sistem, peserta dapat menghubungi Panitia untuk dilakukan pemeriksaan.</p>
    <h2>9. Pembatalan oleh Peserta</h2><p>Pendaftaran yang telah dibayar tidak dapat dibatalkan dengan pengembalian biaya pendaftaran atas permintaan peserta.</p><p>Biaya pendaftaran yang telah berhasil dibayarkan bersifat <strong>non-refundable</strong>, termasuk apabila peserta:</p><ul><li>berubah pikiran atau mengundurkan diri;</li><li>tidak dapat mengikuti kompetisi;</li><li>tidak hadir pada pelaksanaan kompetisi;</li><li>salah memilih kompetisi;</li><li>tidak memenuhi atau tidak menyelesaikan persyaratan kompetisi;</li><li>terlambat melakukan submission;</li><li>didiskualifikasi karena pelanggaran ketentuan; atau</li><li>mengalami keadaan pribadi lainnya yang menyebabkan peserta tidak dapat melanjutkan kompetisi.</li></ul>
    <h2>10. Kesalahan Transaksi Pembayaran</h2><p>Ketentuan non-refundable pada bagian sebelumnya tidak menghilangkan hak peserta untuk melaporkan dugaan kesalahan transaksi pembayaran.</p><p>Apabila terdapat pembayaran ganda, kesalahan nominal, atau kesalahan transaksi yang dapat diverifikasi dan disebabkan oleh sistem pembayaran atau sistem ITB Insight, Panitia akan melakukan pemeriksaan dan rekonsiliasi transaksi.</p><p>Apabila berdasarkan hasil pemeriksaan terdapat dana yang seharusnya tidak diterima oleh Panitia, penyelesaiannya akan dilakukan sesuai hasil verifikasi, prosedur penyedia layanan pembayaran, dan ketentuan yang berlaku.</p><p>Penyelesaian pada kondisi ini merupakan <strong>koreksi transaksi pembayaran</strong> dan bukan pembatalan pendaftaran atas permintaan peserta.</p>
    <h2>11. Pembatalan Kompetisi oleh Panitia</h2><p>Apabila suatu kompetisi <strong>dibatalkan sepenuhnya oleh Panitia dan tidak diselenggarakan</strong>, peserta yang telah melakukan pembayaran berhak memperoleh pengembalian biaya pendaftaran untuk kompetisi tersebut.</p><p>Mekanisme dan jangka waktu pengembalian dana akan diinformasikan kepada peserta melalui kanal resmi ITB Insight.</p><p>Perubahan jadwal, perubahan lokasi, penyesuaian teknis, atau penundaan pelaksanaan tidak secara otomatis dianggap sebagai pembatalan kompetisi.</p>
    <h2>12. Perubahan Jadwal dan Pelaksanaan</h2><p>Panitia dapat melakukan penyesuaian terhadap jadwal, lokasi, mekanisme, atau aspek teknis pelaksanaan apabila diperlukan karena pertimbangan operasional, keselamatan, kebijakan institusi, keadaan di luar kendali Panitia, atau alasan lain yang berkaitan dengan kelangsungan pelaksanaan kegiatan.</p><p>Perubahan tersebut akan diinformasikan melalui kanal resmi ITB Insight.</p><p>Panitia akan berupaya menyampaikan perubahan dalam waktu yang wajar sesuai dengan kondisi yang terjadi.</p>
    <h2>13. Keadaan di Luar Kendali</h2><p>Apabila terjadi keadaan di luar kendali Panitia, termasuk tetapi tidak terbatas pada bencana alam, gangguan keamanan, kebijakan pemerintah atau institusi, gangguan fasilitas, kondisi darurat, atau keadaan lain yang secara wajar memengaruhi pelaksanaan kegiatan, Panitia dapat melakukan penyesuaian, penundaan, perubahan metode pelaksanaan, atau pembatalan kegiatan.</p><p>Ketentuan pengembalian dana mengikuti ketentuan pada bagian <strong>Pembatalan Kompetisi oleh Panitia</strong>.</p>
    <h2>14. Ketentuan dan Kelayakan Peserta</h2><p>Peserta wajib memenuhi seluruh persyaratan yang berlaku pada kompetisi yang diikuti.</p><p>Panitia berhak melakukan verifikasi terhadap identitas, status peserta, institusi, dokumen, karya, dan persyaratan lain yang diberikan selama proses kompetisi.</p><p>Panitia dapat menolak atau membatalkan keikutsertaan peserta apabila ditemukan bahwa peserta tidak memenuhi persyaratan yang berlaku.</p>
    <h2>15. Pelanggaran dan Diskualifikasi</h2><p>Peserta dapat dikenakan sanksi hingga diskualifikasi apabila terbukti melakukan pelanggaran, termasuk tetapi tidak terbatas pada:</p><ul><li>memberikan data atau dokumen yang tidak benar;</li><li>tidak memenuhi persyaratan peserta;</li><li>melakukan kecurangan;</li><li>melakukan plagiarisme atau pelanggaran ketentuan orisinalitas;</li><li>melakukan manipulasi terhadap proses kompetisi;</li><li>melakukan tindakan yang membahayakan peserta lain, Panitia, atau pihak lain;</li><li>melanggar ketentuan keselamatan;</li><li>melakukan tindakan yang mengganggu penyelenggaraan kegiatan; atau</li><li>melanggar guidebook, rulebook, atau ketentuan resmi kompetisi.</li></ul><p>Diskualifikasi tidak memberikan hak atas pengembalian biaya pendaftaran.</p>
    <h2>16. Submission dan Deadline</h2><p>Peserta bertanggung jawab untuk memastikan seluruh submission dikirimkan sebelum batas waktu yang berlaku.</p><p>Ketentuan mengenai format, metode, serta konsekuensi keterlambatan submission mengikuti guidebook, rulebook, atau pengumuman resmi masing-masing kompetisi.</p><p>Submission yang diterima setelah batas waktu <strong>tidak dijamin akan diterima atau dinilai</strong>, kecuali terdapat perpanjangan atau ketentuan lain yang diumumkan secara resmi oleh Panitia.</p>
    <h2>17. Karya dan Kekayaan Intelektual</h2><p>Hak kekayaan intelektual atas karya yang dibuat dan dikumpulkan peserta tetap menjadi milik peserta atau pemegang hak yang sah, kecuali secara khusus dinyatakan lain dalam ketentuan kompetisi.</p><p>Panitia berhak mengakses dan menggunakan karya atau dokumen yang dikumpulkan sejauh diperlukan untuk proses administrasi, verifikasi, penilaian, dan penyelenggaraan kompetisi.</p><p>Penggunaan karya peserta untuk kepentingan lain di luar penyelenggaraan dan dokumentasi kompetisi akan mengikuti ketentuan kompetisi dan persetujuan yang berlaku.</p>
    <h2>18. Dokumentasi Kegiatan</h2><p>Pelaksanaan kegiatan ITB Insight dapat didokumentasikan dalam bentuk foto, video, atau bentuk dokumentasi lainnya.</p><p>Penggunaan dokumentasi yang memuat peserta dilakukan untuk kepentingan dokumentasi, publikasi, dan informasi kegiatan ITB Insight sesuai dengan ketentuan dan persetujuan yang berlaku.</p><p>Untuk peserta yang tergolong anak, penggunaan Data Pribadi dan dokumentasi mengikuti ketentuan mengenai persetujuan orang tua atau wali.</p>
    <h2>19. Data Pribadi</h2><p>Panitia dapat memproses Data Pribadi yang diperlukan untuk:</p><ul><li>pendaftaran peserta;</li><li>verifikasi identitas dan kelayakan;</li><li>administrasi kompetisi;</li><li>pemrosesan dan rekonsiliasi pembayaran;</li><li>komunikasi dengan peserta;</li><li>penyelenggaraan dan penilaian kompetisi;</li><li>penerbitan informasi peserta atau pemenang apabila diperlukan; dan</li><li>pemenuhan kewajiban berdasarkan peraturan yang berlaku.</li></ul><p>Panitia akan membatasi pemrosesan Data Pribadi sesuai dengan kebutuhan penyelenggaraan ITB Insight dan menerapkan langkah yang wajar untuk menjaga keamanan Data Pribadi.</p><p>Ketentuan lebih rinci mengenai jenis data, tujuan pemrosesan, penyimpanan, penghapusan, hak peserta, serta pihak yang dapat menerima Data Pribadi akan diatur dalam <strong>Kebijakan Privasi ITB Insight 2026</strong>.</p>
    <h2>20. Perbedaan Informasi</h2><p>Syarat dan Ketentuan ini mengatur ketentuan umum mengenai penggunaan website, pendaftaran, dan pembayaran.</p><p>Guidebook atau rulebook masing-masing kompetisi mengatur ketentuan teknis kompetisi.</p><p>Apabila terdapat perubahan terhadap informasi yang telah diterbitkan, <strong>pengumuman resmi terbaru yang secara jelas menyatakan perubahan tersebut berlaku sejak tanggal diumumkan</strong>, kecuali disebutkan lain.</p><p>Apabila peserta menemukan informasi yang berbeda atau tidak jelas, peserta dapat meminta konfirmasi melalui kontak resmi ITB Insight.</p>
    <h2>21. Kanal Resmi</h2><p>Informasi dan perubahan terkait ITB Insight dapat disampaikan melalui kanal resmi, antara lain:</p><ul><li>website resmi ITB Insight;</li><li>email resmi ITB Insight; dan</li><li>Instagram <strong>@itbinsight</strong>.</li></ul><p>Peserta bertanggung jawab untuk memantau informasi yang berkaitan dengan kompetisi yang diikuti.</p>
    <h2>22. Perubahan Syarat dan Ketentuan</h2><p>Panitia dapat memperbarui Syarat dan Ketentuan ini apabila diperlukan.</p><p>Perubahan yang bersifat material akan diinformasikan melalui kanal resmi ITB Insight.</p><p>Perubahan berlaku sejak tanggal yang dicantumkan pada versi terbaru Syarat dan Ketentuan dan tidak menghilangkan hak yang telah timbul berdasarkan peraturan perundang-undangan yang berlaku.</p>
    <h2>23. Hukum yang Berlaku</h2><p>Syarat dan Ketentuan ini tunduk pada hukum dan peraturan perundang-undangan yang berlaku di Republik Indonesia.</p>
    <h2>24. Kontak</h2><p>Untuk pertanyaan mengenai pendaftaran, pembayaran, atau Syarat dan Ketentuan ITB Insight 2026, peserta dapat menghubungi:</p><p><strong>Email:</strong> support@itbinsight.com<br /><strong>Instagram:</strong> @itbinsight</p><p>Dengan mencentang kotak persetujuan pada saat pendaftaran, ketua tim menyatakan telah membaca, memahami, dan menyetujui Syarat dan Ketentuan ITB Insight 2026.</p>
  </article></main></>
}
